#!/usr/bin/perl

print "Enter a value: ";
chomp($a = <STDIN>);

print "Enter b value: ";
chomp($b = <STDIN>);

print "Enter c value: ";
chomp($c = <STDIN>);

# Determine the largest value
if ($a > $b && $a > $c) {
    print "$a is the largest number\n";
} elsif ($b > $c) {
    print "$b is the largest number\n";
} else {
    print "$c is the largest number\n";
}
