#!/usr/bin/perl
use strict;
use warnings;

# Subroutine to print multiplication table for a given number
sub print_multiplication_table {
    my ($n) = @_;
    print "Multiplication table of $n:\n";
    for (my $i = 1; $i <= 10; $i++) {
        my $m = $n * $i;
        print "$n * $i = $m\n";
    }
    print "\n";
}

# Main script
print "Enter the number: ";
chomp(my $n = <STDIN>);

# Call the subroutine to print the multiplication table
print_multiplication_table($n);
